/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "shipease-orange": "#f97316",
        "shipease-orange-hover": "#ea580c",
        "shipease-navy": "#0f172a",
        "secondary": "#006e2f",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface": "#191b23",
        "tertiary-fixed-dim": "#ffb596",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-container": "#6bff8f",
        "on-tertiary-container": "#ffede6",
        "secondary-fixed-dim": "#4ae176",
        "on-surface-variant": "#434655",
        "on-secondary-fixed-variant": "#005321",
        "surface-container-highest": "#e1e2ed",
        "tertiary-fixed": "#ffdbcd",
        "on-error": "#ffffff",
        "primary-container": "#2563eb",
        "surface-container-high": "#e7e7f3",
        "surface-tint": "#0053db",
        "error": "#ba1a1a",
        "primary": "#004ac6",
        "on-primary": "#ffffff",
        "outline": "#737686",
        "outline-variant": "#c3c6d7",
        "on-primary-container": "#eeefff",
        "on-primary-fixed": "#00174b",
        "background": "#faf8ff",
        "tertiary-container": "#bc4800",
        "on-background": "#191b23",
        "on-secondary-fixed": "#002109",
        "surface-container-low": "#f3f3fe",
        "surface": "#faf8ff",
        "secondary-fixed": "#6bff8f",
        "inverse-surface": "#2e3039",
        "surface-dim": "#d9d9e5",
        "inverse-primary": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-bright": "#faf8ff",
        "tertiary": "#943700",
        "error-container": "#ffdad6",
        "surface-container": "#ededf9",
        "primary-fixed": "#dbe1ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#360f00",
        "surface-variant": "#e1e2ed",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-secondary-container": "#007432",
        "inverse-on-surface": "#f0f0fb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "label-sm": ["Inter"], "h1": ["Inter"], "h2": ["Inter"], "display": ["Inter"], "body-sm": ["Inter"], "body-lg": ["Inter"], "body-md": ["Inter"], "h3": ["Inter"], "label-md": ["Inter"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h1": ["30px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "h2": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "h3": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.2", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
